<?php
use Nette\SmartCachingIterator;

$sanite = function($var){
	return htmlspecialchars(is_bool($var) ? ($var?'TRUE':'FALSE') : $var);
}

?>

<h3>Request</h3>
<table>
<?php $list = array(
	'cookieFile' => "Cookie file",
	'downloadFolder' => "Download folder",
	'downloadPath' => "Download path",
	'followRedirects' => "Follow redirects",
	'headers' => "Headers",
	'info' => "Info",
	'method' => "Method",
	'options' => "Options",
	'proxies' => "Proxies",
	'referer' => "Referer",
	'userAgent' => "User agent",
	'url' => "Url",
	'vars' => "Vars"
	);
foreach ($iterator = new SmartCachingIterator($list) as $property => $name): ?>
<?php if(isset($request->{$property}) && !empty($request->{$property})): ?>
<?php $odd = ($iterator->isOdd()?' class="odd"':NULL); ?>
<tr<?=$odd?>>
	<th><?=$name?></th><td><?php if(is_array($request->{$property})): ?>
	<?php foreach ($request->{$property} as $key => $value): ?>
		<?=$sanite($key).': '.$sanite((string)$value)."<br>" ?>
	<?php endforeach; else: ?>
		<?=$sanite($request->{$property})?>
	<?php endif; ?></td>
</tr>
<?php endif; endforeach; ?>
</table>

<h3>Response</h3>
<?php if(!$response->headers): ?>
<p>No response</p>
<?php else: ?>
<table>
<?php $list = array(
	'headers' => "Headers",
	);
foreach ($iterator = new SmartCachingIterator($list) as $property => $name): ?>
<?php if(isset($response->{$property}) && !empty($response->{$property})): ?>
<?php $odd = ($iterator->isOdd()?' class="odd"':NULL); ?>
<tr<?=$odd?>>
	<th><?=$name?></th><td><?php if(is_array($response->{$property})): ?>
	<?php foreach ($response->{$property} as $key => $value): ?>
		<?=$sanite($key).': '.$sanite((string)$value)."<br>" ?>
	<?php endforeach; else: ?>
		<?=$sanite($response->{$property})?>
	<?php endif; ?></td>
</tr>
<?php endif; endforeach; ?>
</table>
<?php endif; ?>